#!/usr/bin/env sh

DIR=$(dirname $(readlink -f $0))

if command -v rlwrap > /dev/null
then
    rlwrap $DIR/binary_calc.py
else
    echo "Install rlwrap to support arrow keys in binary_calc"
    $DIR/binary_calc.py
fi
